### ISSUE TITLE
Navigation Bar

### ISSUE THREAD

**Issue by danielc2013** [danielc2013/jokeroulette#7]
The navigation bar just needs to be a nav with a few anchor tags (probably embedded in a ul > li schema). make sure there is an option for each of the three views and a main page link and a fifth which leads to the account page. Place the nav in its own html snippet in a sub folder named fragments. First we'll add it by hand to each view. Later we'll use javascript to load fragments dynamically.

**Comment by clunaslunas** [comment]
So I am going to do my best at making a nav bar anchor tags and such but I will need a little review on HTML Snippets

**Comment by danielc2013** [comment]
All you have to do is write the nav code in another html file. Dont add the head or body just the nav. basically
<nav>

</nav>
Then save this in an html file inside of a directory (which you need to also make) named fragments. Also, when you assign a card to yourself in waffle, make sure to move it to the in-progress column
